### ISSUE TITLE
Question: How get the empirical Bayes posterior estimate

### ISSUE THREAD

**Issue by alexhallam** [bnaras/deconvolveR#1]
I have been reading the paper this package is associated with along with _Computer Age Statistical Inference_. The paper has been very clear with great examples, but I am a little confused about how to find the posterior empirical Bayes estimate, specifically in the nodes example. For example, I use the following lines of code:

```
tau <- seq(from = 0.01, to = 0.99, by = 0.01)
result <- deconv(tau = tau, X = surg, family = "Binomial")
results$stats
```

From this I get g(theta). In Brad Efron's book he is able to then plug in the values `x=3` and `n=6` to get an empirical Bayes estimate of `0.446`.

The example I am referring to is on page 88, equation 6.44 of _Computer Age Statistical Inference_. 

My question is, how do I use this package to calculate empirical Bayes estimates such as shown in equation 6.44?

**Comment by bnaras** [comment]
You would use the discrete distribution g(theta) to do so pretty much following the formulas on those pages.  My answer 0.453516 is close but not exact.

```{r}
theta <- result$stats[, 'theta']
gTheta <- result$stats[, 'g']

f_alpha <- function(n_k, x_k) {
    ## .01 is the delta_theta in the Riemann sum
    sum(dbinom(x = x_k, size = n_k, prob = theta) * gTheta) * .01
}

g_theta_hat <- function(n_k, x_k) {
    gTheta * dbinom(x = x_k, size = n_k, prob = theta) / f_alpha(n_k, x_k)
}

g1 <- g_theta_hat(x_k = 7, n_k = 32)
g2 <- g_theta_hat(x_k = 3, n_k = 6)
g3 <- g_theta_hat(x_k = 17, n_k = 18)

library(ggplot2)
p <- ggplot2::ggplot() +
    ggplot2::geom_line(mapping = aes(x = theta, y = g1), col = "magenta") +
    ggplot2::ylim(0, 10) +
    ggplot2::geom_line(mapping = aes(x = theta, y = g2), col = "red") +
    ggplot2::geom_line(mapping = aes(x = theta, y = g3), col = "blue") +
    ggplot2::labs(x = expression(theta), y = expression(g(paste(theta, "|(x, n)"))))

print(p)

## .01 is the delta_theta in the Riemann sum
cat(sprintf("Approximate Eqn 6.44 value: %f\n", 0.01 * sum(theta * g2)))
```

**Comment by alexhallam** [comment]
Perfect! Thanks. This package and your [simulations](https://cran.r-project.org/web/packages/deconvolveR/vignettes/deconvolution.html) make deconvolution much easier to understand.
