### ISSUE TITLE
Feature Request: Add example with covariates to vignette 

### ISSUE THREAD

**Issue by alexhallam** [bnaras/deconvolveR#4]
**I found an example from the Biometrika paper where Brad Efron adds covariates as follows**

<img width="566" alt="example" src="https://user-images.githubusercontent.com/9298693/36747981-848ea758-1bc4-11e8-8ec0-febd048dce0c.PNG">

**I was wondering if a short example of this code existed or if it could be added to the vignette**

**Comment by barakbri** [comment]
I was looking for the same code example, is there a link available?
Thanks
